# Generated by Django 4.0.6 on 2022-11-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_remove_sub_course_teachers_sub_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='teacher',
        ),
        migrations.AddField(
            model_name='sub',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tg_bot.course'),
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
